### ISSUE TITLE
I keep having this issue with the Parts of the model will be large for some reason

### ISSUE THREAD

**Issue by Nixet91** [arikidev/MoveStyler#4]
![IMG_3742](https://github.com/arikidev/MoveStyler/assets/171521167/3ddebd3b-44ae-4e18-b8f1-70c6b726d90c)
![IMG_3741](https://github.com/arikidev/MoveStyler/assets/171521167/7bdb3a0e-2177-4ce0-bb34-8f971e2fdc7f)
![IMG_3743](https://github.com/arikidev/MoveStyler/assets/171521167/eb1b16fc-a3a4-45dc-a1c6-17d21d50b59c)

**Comment by arikidev** [comment]
This happens if the hop movestyle is not installed correctly. Ensure the the hop movestyle plugin is installed in the plugins folder of your installation.
